# Generated by Django 2.2.6 on 2020-06-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200622_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
