# Generated by Django 2.2.6 on 2020-06-22 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200622_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
