# Generated by Django 2.2.6 on 2020-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200623_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='file',
            field=models.FileField(default='p.json', upload_to='files'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
