# Generated by Django 2.2.6 on 2020-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200623_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='title',
            field=models.CharField(default='myfile', max_length=50),
        ),
    ]
